name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ML_API_KEY: ${{ secrets.ML_API_KEY }}
          EMAIL_API_KEY: ${{ secrets.EMAIL_API_KEY }}
          ADMIN_SECRET_KEY: ${{ secrets.ADMIN_SECRET_KEY }}
        run: |
          echo $DB_USERNAME
     
      # Add deployment steps here, accessing sensitive data as needed
